/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/banquet': RouteRecordInfo<'/banquet', '/banquet', Record<never, never>, Record<never, never>>,
    '/banquetLogin': RouteRecordInfo<'/banquetLogin', '/banquetLogin', Record<never, never>, Record<never, never>>,
    '/counter': RouteRecordInfo<'/counter', '/counter', Record<never, never>, Record<never, never>>,
    '/counterLogin': RouteRecordInfo<'/counterLogin', '/counterLogin', Record<never, never>, Record<never, never>>,
    '/parking': RouteRecordInfo<'/parking', '/parking', Record<never, never>, Record<never, never>>,
    '/shop': RouteRecordInfo<'/shop', '/shop', Record<never, never>, Record<never, never>>,
    '/shopLogin': RouteRecordInfo<'/shopLogin', '/shopLogin', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/banquet.vue': {
      routes: '/banquet'
      views: never
    }
    'src/pages/banquetLogin.vue': {
      routes: '/banquetLogin'
      views: never
    }
    'src/pages/counter.vue': {
      routes: '/counter'
      views: never
    }
    'src/pages/counterLogin.vue': {
      routes: '/counterLogin'
      views: never
    }
    'src/pages/parking.vue': {
      routes: '/parking'
      views: never
    }
    'src/pages/shop.vue': {
      routes: '/shop'
      views: never
    }
    'src/pages/shopLogin.vue': {
      routes: '/shopLogin'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
